import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import BaseLayout from '@/core/layout/base-layout';
import AmplitudeContextProvider from '@/core/providers/amplitude';
import '@workspace/ui/styles/globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AmplitudeContextProvider>
          <BaseLayout>{children}</BaseLayout>
        </AmplitudeContextProvider>
      </body>
    </html>
  );
}
