# Config file for air
[build]
  cmd = "swag init -g ./cmd/api/main.go --dir=./ --output=./docs && go build -gcflags 'all=-N -l'  -o ./tmp/dappas-api ./cmd/api/main.go"
  bin = "./tmp/dappas-api"
  full_bin = "APP_ENV=dev dlv exec ./tmp/dappas-api --listen=:40000 --headless=true --api-version=2 --accept-multiclient --continue --log --"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor", "docs", "uploads"]
  exclude_file = ["air.toml"]
  delay = 1000 # ms
  log = "air_errors.log"
  stop_on_error = true
  kill_delay = 500 # ms
  poll = true

[log]
  color = true
  timestamp = false
  highlight = true