services:
  dappas-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=password
      - DB_NAME=dappasdb
      - ENV=development
      - DAPPAS_ADMIN_PASSWORD=admin
      - DAPPAS_ADMIN_EMAIL=admin@dappas.com
      - SHOPIFY_API_KEY=6a7e77c25e50cc700cb06a1353bddbb4
      - SHOPIFY_API_SECRET=6338c1682ff7a9c0933cb80aed090b36
      - SHOPIFY_API_SCOPES=read_products,write_products
      - SHOPIFY_API_REDIRECT_URI=http://localhost:8080/v1/ecommerce/shopify/auth-callback
    depends_on:
      postgres:
        condition: service_healthy
      migrator:
        condition: service_started
    networks:
      - app-network
    restart: on-failure
  migrator:
    build:
      context: .
      dockerfile: Dockerfile.migrator
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=password
      - DB_NAME=dappasdb
      - DAPPAS_ADMIN_PASSWORD=admin
      - DAPPAS_ADMIN_EMAIL=admin@dappas.com
      - DAPPAS_ADMIN_FIRST_NAME=Dappas 
      - DAPPAS_ADMIN_LAST_NAME=Admin
      - SHOPIFY_API_KEY=6a7e77c25e50cc700cb06a1353bddbb4
      - SHOPIFY_API_SECRET=6338c1682ff7a9c0933cb80aed090b36
      - SHOPIFY_API_SCOPES=read_products,write_products
      - SHOPIFY_API_REDIRECT_URI=http://localhost:8080/v1/ecommerce/shopify/auth-callback
      
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    restart: "no"
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dappasdb
    ports:
      - '5432:5432'
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network

networks:
  app-network:
