// Code generated by MockGen. DO NOT EDIT.
// Source: selector.dev/dappas/internal/modules/vendors/usecases (interfaces: IListVendorsUseCase)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_list_vendors_usecase.go -package=mocks selector.dev/dappas/internal/modules/vendors/usecases IListVendorsUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	models "selector.dev/dappas/internal/modules/vendors/models"
)

// MockIListVendorsUseCase is a mock of IListVendorsUseCase interface.
type MockIListVendorsUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockIListVendorsUseCaseMockRecorder
	isgomock struct{}
}

// MockIListVendorsUseCaseMockRecorder is the mock recorder for MockIListVendorsUseCase.
type MockIListVendorsUseCaseMockRecorder struct {
	mock *MockIListVendorsUseCase
}

// NewMockIListVendorsUseCase creates a new mock instance.
func NewMockIListVendorsUseCase(ctrl *gomock.Controller) *MockIListVendorsUseCase {
	mock := &MockIListVendorsUseCase{ctrl: ctrl}
	mock.recorder = &MockIListVendorsUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIListVendorsUseCase) EXPECT() *MockIListVendorsUseCaseMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockIListVendorsUseCase) Run(input *models.ListVendorsInput) (*models.ListVendorsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", input)
	ret0, _ := ret[0].(*models.ListVendorsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockIListVendorsUseCaseMockRecorder) Run(input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockIListVendorsUseCase)(nil).Run), input)
}
