// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	dtos "selector.dev/pulse/internal/application/dtos"
)

// PayerService is an autogenerated mock type for the PayerService type
type PayerService struct {
	mock.Mock
}

// CreatePayer provides a mock function with given fields: input
func (_m *PayerService) CreatePayer(input *dtos.CreatePayerInput) (*dtos.CreatedOutput, error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayer")
	}

	var r0 *dtos.CreatedOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(*dtos.CreatePayerInput) (*dtos.CreatedOutput, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(*dtos.CreatePayerInput) *dtos.CreatedOutput); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.CreatedOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(*dtos.CreatePayerInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeletePayer provides a mock function with given fields: id
func (_m *PayerService) DeletePayer(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeletePayer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPayerById provides a mock function with given fields: id
func (_m *PayerService) GetPayerById(id uint) (*dtos.Payer, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetPayerById")
	}

	var r0 *dtos.Payer
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*dtos.Payer, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *dtos.Payer); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.Payer)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPayers provides a mock function with given fields: input
func (_m *PayerService) GetPayers(input *dtos.PayerFilterInput) (*dtos.Payers, error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for GetPayers")
	}

	var r0 *dtos.Payers
	var r1 error
	if rf, ok := ret.Get(0).(func(*dtos.PayerFilterInput) (*dtos.Payers, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(*dtos.PayerFilterInput) *dtos.Payers); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.Payers)
		}
	}

	if rf, ok := ret.Get(1).(func(*dtos.PayerFilterInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPayersAsNomenclator provides a mock function with no fields
func (_m *PayerService) GetPayersAsNomenclator() (*dtos.Nomenclators, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPayersAsNomenclator")
	}

	var r0 *dtos.Nomenclators
	var r1 error
	if rf, ok := ret.Get(0).(func() (*dtos.Nomenclators, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *dtos.Nomenclators); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.Nomenclators)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePayer provides a mock function with given fields: input
func (_m *PayerService) UpdatePayer(input *dtos.UpdatePayerInput) (*dtos.Payer, error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePayer")
	}

	var r0 *dtos.Payer
	var r1 error
	if rf, ok := ret.Get(0).(func(*dtos.UpdatePayerInput) (*dtos.Payer, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(*dtos.UpdatePayerInput) *dtos.Payer); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.Payer)
		}
	}

	if rf, ok := ret.Get(1).(func(*dtos.UpdatePayerInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPayerService creates a new instance of PayerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPayerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PayerService {
	mock := &PayerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
