import { AdminDashboardSummary, AdminInvoices } from '@/server/types/admin';
import { ComboBoxOption } from '@/server/types/combo-box';

export const invoices: AdminInvoices[] = [
  {
    id: 1,
    advertiser: 'Company A',
    company: 'Advertising Inc.',
    production: 'Video Production',
    balance: 5000,
    status: 'UPLOADED',
    advance_amount: 1500,
  },
  {
    id: 2,
    advertiser: 'Company B',
    company: 'Marketing Co.',
    production: 'Event Marketing',
    balance: 3000,
    status: 'APPROVED',
    advance_amount: 1000,
  },
  {
    id: 3,
    advertiser: 'Company C',
    company: 'Creative Agency',
    production: 'Graphic Design',
    balance: 2500,
    status: 'PAID',
    advance_amount: 500,
  },
  {
    id: 4,
    advertiser: 'Company D',
    company: 'Digital Solutions',
    production: 'Web Development',
    balance: 7000,
    status: 'UPLOADED',
    advance_amount: 2000,
  },
  {
    id: 5,
    advertiser: 'Company E',
    company: 'Media Corp.',
    production: 'Social Media Campaign',
    balance: 4500,
    status: 'APPROVED',
    advance_amount: 1200,
  },
  {
    id: 6,
    advertiser: 'Company F',
    company: 'Brand Builders',
    production: 'SEO Services',
    balance: 3600,
    status: 'PAID',
    advance_amount: 800,
  },
  {
    id: 7,
    advertiser: 'Company G',
    company: 'Content Creators',
    production: 'Content Writing',
    balance: 4000,
    status: 'UPLOADED',
    advance_amount: 1000,
  },
  {
    id: 8,
    advertiser: 'Company H',
    company: 'Ad Ventures',
    production: 'Commercial Production',
    balance: 5500,
    status: 'APPROVED',
    advance_amount: 1800,
  },
  {
    id: 9,
    advertiser: 'Company I',
    company: 'Visual Media',
    production: 'Photography Services',
    balance: 2000,
    status: 'PAID',
    advance_amount: 400,
  },
  {
    id: 10,
    advertiser: 'Company J',
    company: 'Design Experts',
    production: 'Brand Development',
    balance: 6000,
    status: 'UPLOADED',
    advance_amount: 1700,
  },
  {
    id: 1,
    advertiser: 'Company A',
    company: 'Advertising Inc.',
    production: 'Video Production',
    balance: 5000,
    status: 'UPLOADED',
    advance_amount: 1500,
  },
  {
    id: 2,
    advertiser: 'Company B',
    company: 'Marketing Co.',
    production: 'Event Marketing',
    balance: 3000,
    status: 'APPROVED',
    advance_amount: 1000,
  },
  {
    id: 3,
    advertiser: 'Company C',
    company: 'Creative Agency',
    production: 'Graphic Design',
    balance: 2500,
    status: 'PAID',
    advance_amount: 500,
  },
  {
    id: 4,
    advertiser: 'Company D',
    company: 'Digital Solutions',
    production: 'Web Development',
    balance: 7000,
    status: 'UPLOADED',
    advance_amount: 2000,
  },
  {
    id: 5,
    advertiser: 'Company E',
    company: 'Media Corp.',
    production: 'Social Media Campaign',
    balance: 4500,
    status: 'APPROVED',
    advance_amount: 1200,
  },
  {
    id: 6,
    advertiser: 'Company F',
    company: 'Brand Builders',
    production: 'SEO Services',
    balance: 3600,
    status: 'PAID',
    advance_amount: 800,
  },
  {
    id: 7,
    advertiser: 'Company G',
    company: 'Content Creators',
    production: 'Content Writing',
    balance: 4000,
    status: 'UPLOADED',
    advance_amount: 1000,
  },
  {
    id: 8,
    advertiser: 'Company H',
    company: 'Ad Ventures',
    production: 'Commercial Production',
    balance: 5500,
    status: 'APPROVED',
    advance_amount: 1800,
  },
  {
    id: 9,
    advertiser: 'Company I',
    company: 'Visual Media',
    production: 'Photography Services',
    balance: 2000,
    status: 'PAID',
    advance_amount: 400,
  },
  {
    id: 10,
    advertiser: 'Company J',
    company: 'Design Experts',
    production: 'Brand Development',
    balance: 6000,
    status: 'UPLOADED',
    advance_amount: 1700,
  },
  {
    id: 1,
    advertiser: 'Company A',
    company: 'Advertising Inc.',
    production: 'Video Production',
    balance: 5000,
    status: 'UPLOADED',
    advance_amount: 1500,
  },
  {
    id: 2,
    advertiser: 'Company B',
    company: 'Marketing Co.',
    production: 'Event Marketing',
    balance: 3000,
    status: 'APPROVED',
    advance_amount: 1000,
  },
  {
    id: 3,
    advertiser: 'Company C',
    company: 'Creative Agency',
    production: 'Graphic Design',
    balance: 2500,
    status: 'PAID',
    advance_amount: 500,
  },
  {
    id: 4,
    advertiser: 'Company D',
    company: 'Digital Solutions',
    production: 'Web Development',
    balance: 7000,
    status: 'UPLOADED',
    advance_amount: 2000,
  },
  {
    id: 5,
    advertiser: 'Company E',
    company: 'Media Corp.',
    production: 'Social Media Campaign',
    balance: 4500,
    status: 'APPROVED',
    advance_amount: 1200,
  },
  {
    id: 6,
    advertiser: 'Company F',
    company: 'Brand Builders',
    production: 'SEO Services',
    balance: 3600,
    status: 'PAID',
    advance_amount: 800,
  },
  {
    id: 7,
    advertiser: 'Company G',
    company: 'Content Creators',
    production: 'Content Writing',
    balance: 4000,
    status: 'UPLOADED',
    advance_amount: 1000,
  },
  {
    id: 8,
    advertiser: 'Company H',
    company: 'Ad Ventures',
    production: 'Commercial Production',
    balance: 5500,
    status: 'APPROVED',
    advance_amount: 1800,
  },
  {
    id: 9,
    advertiser: 'Company I',
    company: 'Visual Media',
    production: 'Photography Services',
    balance: 2000,
    status: 'PAID',
    advance_amount: 400,
  },
  {
    id: 10,
    advertiser: 'Company J',
    company: 'Design Experts',
    production: 'Brand Development',
    balance: 6000,
    status: 'UPLOADED',
    advance_amount: 1700,
  },
  {
    id: 1,
    advertiser: 'Company A',
    company: 'Advertising Inc.',
    production: 'Video Production',
    balance: 5000,
    status: 'UPLOADED',
    advance_amount: 1500,
  },
  {
    id: 2,
    advertiser: 'Company B',
    company: 'Marketing Co.',
    production: 'Event Marketing',
    balance: 3000,
    status: 'APPROVED',
    advance_amount: 1000,
  },
  {
    id: 3,
    advertiser: 'Company C',
    company: 'Creative Agency',
    production: 'Graphic Design',
    balance: 2500,
    status: 'PAID',
    advance_amount: 500,
  },
  {
    id: 4,
    advertiser: 'Company D',
    company: 'Digital Solutions',
    production: 'Web Development',
    balance: 7000,
    status: 'UPLOADED',
    advance_amount: 2000,
  },
  {
    id: 5,
    advertiser: 'Company E',
    company: 'Media Corp.',
    production: 'Social Media Campaign',
    balance: 4500,
    status: 'APPROVED',
    advance_amount: 1200,
  },
  {
    id: 6,
    advertiser: 'Company F',
    company: 'Brand Builders',
    production: 'SEO Services',
    balance: 3600,
    status: 'PAID',
    advance_amount: 800,
  },
  {
    id: 7,
    advertiser: 'Company G',
    company: 'Content Creators',
    production: 'Content Writing',
    balance: 4000,
    status: 'UPLOADED',
    advance_amount: 1000,
  },
  {
    id: 8,
    advertiser: 'Company H',
    company: 'Ad Ventures',
    production: 'Commercial Production',
    balance: 5500,
    status: 'APPROVED',
    advance_amount: 1800,
  },
  {
    id: 9,
    advertiser: 'Company I',
    company: 'Visual Media',
    production: 'Photography Services',
    balance: 2000,
    status: 'PAID',
    advance_amount: 400,
  },
  {
    id: 10,
    advertiser: 'Company J',
    company: 'Design Experts',
    production: 'Brand Development',
    balance: 6000,
    status: 'UPLOADED',
    advance_amount: 1700,
  },
];

export const companies: ComboBoxOption[] = [
  { label: 'Google', value: 'google' },
  { label: 'Microsoft', value: 'microsoft' },
  { label: 'Apple', value: 'apple' },
  { label: 'Amazon', value: 'amazon' },
  { label: 'Meta', value: 'meta' },
  { label: 'Tesla', value: 'tesla' },
  { label: 'Netflix', value: 'netflix' },
  { label: 'Spotify', value: 'spotify' },
  { label: 'Salesforce', value: 'salesforce' },
  { label: 'Adobe', value: 'adobe' },
];

export const productions: ComboBoxOption[] = [
  { label: 'Universal Pictures', value: 'universal_pictures' },
  { label: 'Warner Bros', value: 'warner_bros' },
  { label: 'Paramount Pictures', value: 'paramount_pictures' },
  { label: 'Sony Pictures', value: 'sony_pictures' },
  { label: '20th Century Studios', value: '20th_century_studios' },
  { label: 'MGM Studios', value: 'mgm_studios' },
  { label: 'Lionsgate', value: 'lionsgate' },
  { label: 'Pixar', value: 'pixar' },
  { label: 'DreamWorks', value: 'dreamworks' },
  { label: 'Illumination', value: 'illumination' },
];

export const advertisers: ComboBoxOption[] = [
  { label: 'Coca-Cola', value: 'coca_cola' },
  { label: 'Nike', value: 'nike' },
  { label: 'Pepsi', value: 'pepsi' },
  { label: "McDonald's", value: 'mcdonalds' },
  { label: 'Procter & Gamble', value: 'procter_gamble' },
  { label: 'Unilever', value: 'unilever' },
  { label: 'Samsung', value: 'samsung' },
  { label: 'Toyota', value: 'toyota' },
  { label: "L'Oréal", value: 'loreal' },
  { label: 'Disney', value: 'disney' },
];

export const invoiceStatus: ComboBoxOption[] = [
  { label: 'Uploaded', value: 'UPLOADED' },
  { label: 'Approved', value: 'APPROVED' },
  { label: 'Paid', value: 'PAID' },
];


export const adminDashboardSummary: AdminDashboardSummary = {
  additional_available_to_advance: 7000000,
  total_accounts_receivable_approved: 85000000,
  total_accounts_receivable_waiting_approved: 12000000,
  total_advances_outstanding: 53000000
}