FROM golang:alpine

WORKDIR /app

RUN apk add --no-cache gcc musl-dev
RUN apk add --no-cache postgresql-client

COPY . .
RUN go mod download

RUN go build -o migrator cmd/migrator/main.go

ENTRYPOINT ["./migrator"]