export const pathsNames: Record<string, string> = {
  dashboard: 'Dashboard',
  receivables: 'Receivables',
  production: 'Production',
  overview: 'Overview',
  booking: 'Booking',
  payable: 'Payable',
  expenses: 'Expenses',
  invoices: 'Invoices',
  payers: 'Payers',
  'new-payer': 'New payer',
  'new-expense': 'New expense',
  expense_details: 'Expense details',
  'insertion-orders': 'Insertion orders',
  flights: 'Flights',
  payables: 'Payables',
  productions: 'Productions',
  edit_production: 'Edit production',
  bills: 'Bills',
  'user-management': 'User management',
  'create-user': 'Create user',
  'edit-user': 'Edit user',
  drafts: 'Drafts',
  'edit-expense': 'Edit expense',
  details: 'Details',
  new: 'New',
  edit: 'Edit',
  'activity-logs': 'Activity logs',
  'expense-details': 'Expense details',
  'register-expense': 'Register expense',
};
