name: pull-request-review

on:
  #push:
  #  branches:
  #    - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      # Install go dependencies 
      - name: Use Go 1.23.2
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.2
        
      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Install dependencies
      - run: npm ci
      - run: npm install --legacy-peer-deps --prefix ./apps/dappas-web 

      - uses: nrwl/nx-set-shas@v4

      # Validate all commits from PR
      - name: Validate all commits from PR
        run: |
          # Get the base and head commits of the pull request
          BASE_SHA=$(git merge-base origin/${{ github.event.pull_request.base.ref }} HEAD)
          HEAD_SHA=${{ github.sha }}

          echo "Linting commits from $BASE_SHA to $HEAD_SHA"

          # Run commitlint on the range of commits
          npx commitlint --from $BASE_SHA --to $HEAD_SHA --verbose
      
        # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: npx nx-cloud record -- echo Hello World
      # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
      - run: npx nx affected -t lint test build --verbose --no-cloud
